### ISSUE TITLE
Crashing on podium

### ISSUE THREAD

**Issue by Skorlok** [lythx/trakman#208]
Yo, the controller is crashing at the begining of the podium

<FATAL> [30 Apr 2023 02:05:20] (Logger.js:28) Unhandled rejection occured:
        Cannot read properties of undefined (reading 'callerLogin')
        TypeError: Cannot read properties of undefined (reading 'callerLogin')
            at Object.callback (file:///home/TM/TMUF/Trakman/TMN/built/src/Listeners.js:245:55)
            at Object.emit (file:///home/TM/TMUF/Trakman/TMN/built/src/Events.js:66:18)
            at ClientSocket.handleResponseChunk (file:///home/TM/TMUF/Trakman/TMN/built/src/client/ClientSocket.js:120:24)
            at ClientSocket.handleResponseStart (file:///home/TM/TMUF/Trakman/TMN/built/src/client/ClientSocket.js:107:14)
            at ClientSocket.handleResponseChunk (file:///home/TM/TMUF/Trakman/TMN/built/src/client/ClientSocket.js:125:18)
            at ClientSocket.handleResponseStart (file:///home/TM/TMUF/Trakman/TMN/built/src/client/ClientSocket.js:107:14)
            at ClientSocket.handleResponseChunk (file:///home/TM/TMUF/Trakman/TMN/built/src/client/ClientSocket.js:125:18)
            at ClientSocket.handleResponseStart (file:///home/TM/TMUF/Trakman/TMN/built/src/client/ClientSocket.js:107:14)
            at ClientSocket.handleResponseChunk (file:///home/TM/TMUF/Trakman/TMN/built/src/client/ClientSocket.js:125:18)
            at ClientSocket.handleResponseStart (file:///home/TM/TMUF/Trakman/TMN/built/src/client/ClientSocket.js:107:14)

i'm using the latest version [1.3.2], freshly installed

**Comment by Skorlok** [comment]
![putty_7QqlomJgkL](https://user-images.githubusercontent.com/70608768/235332205-e4513b4b-82e7-4bd5-9cbc-3a4cfcc559fd.png)

**Comment by wsrvn** [comment]
do you only have one map on the server?

**Comment by Skorlok** [comment]
I have 236 maps

**Comment by Skorlok** [comment]
btw when I configured the server I don't spell the good database, after correcting it I had many crashes and I had the rebuilt/relaunch many times to fix them.

**Comment by wsrvn** [comment]
database errors are a known issue, usually restarting a few times gets that fixed, as you pointed out. that can only happen on an empty database as far as i know, we haven't really done many testing with that. 

for the endmap crash, it would appear that the very next map in the queue is undefined, which hasn't happened to us in the last 6+ months of testing. we'll make an attempt to fix it in the coming days, whenever time allows.

if you want to test other functionality, i'd suggest removing the if block at around line 237 of the listeners file (or perhaps keep queue config opti9n is the culprit? it's somewhat recent).

**Comment by Skorlok** [comment]
I reinstalled it again and the issue is somehow fixed. But not the database error (i recompiled 4 times and it's done)
I might be autist I did the same steps to start it

**Comment by wsrvn** [comment]
> I reinstalled it again and the issue is somehow fixed. But not the database error (i recompiled 4 times and it's done)
> I might be autist I did the same steps to start it

interesting. we will need proper testing either way tho.
