### ISSUE TITLE
Controller not start when DISCORD_LOG_LEVEL is 3

### ISSUE THREAD

**Issue by xadll** [lythx/trakman#240]
[Wiki page](https://github.com/lythx/trakman/wiki/Manual-Installation#controller-configuration) says that allowed numbers range is from 1 to 5.

When i set DISCORD_LOG_LEVEL within docker-compose.yaml to `DISCORD_LOG_LEVEL: 3`, controller wont start.

Logs:
```
TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.strip (file:///app/server/trakman/src/Utils.ts:78:16)
    at Function.writeLog (file:///app/server/trakman/src/Logger.ts:205:61)
    at Function.fatal (file:///app/server/trakman/src/Logger.ts:120:5)
TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.strip (file:///app/server/trakman/src/Utils.ts:78:16)
    at Function.writeLog (file:///app/server/trakman/src/Logger.ts:205:61)
```

**Comment by wsrvn** [comment]
this is due to the controller not having the information about the server name/login on startup (as the gameservice starts later), will be fixed in the next version, for now set the log to 2
